[package]
name = "server-v1"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "1.18.14"
solana-sdk = "1.18.14"
spl-token = "4.0"
bs58 = "0.5"
base64 = "0.21"
serde_json = "1.0.140"
base58 = "0.2"
actix-web = "4.11.0"
serde = "1.0.219"

